#!/usr/bin/env python3
"""
about_info.py
=============
Central place for the tool's identity, feature list and how-to text. Used by the
GUI's About dialog and by the splash/icon generator. Keeping it here means the
information appears identically everywhere and is trivial to update.
"""

APP_NAME = "PDF Image Remover"
TAGLINE = "Image Remover \u00b7 LaTeX \u00b7 Markdown converter"
VERSION = "2.0"
AUTHOR = "Jerry James"
LICENSE = "GPL-3.0 (GNU General Public License v3.0)"
COPYRIGHT = "Copyright (C) 2026 Jerry James"
PROJECT_URL = "https://github.com/"  # update to your repository URL

DESCRIPTION = (
    "A desktop tool for working with PDF papers. It can strip images from a "
    "PDF while keeping all text and the exact layout, or convert a PDF into a "
    "clean, compilable IEEE LaTeX project or a full-text Markdown file \u2014 "
    "formats that any AI tool can read without having to process the PDF."
)

FEATURES = [
    "Remove images (raster only) \u2014 keeps charts, tables, equations and "
    "the exact text layout. Clears AI image-upload limits.",
    "Remove images + figures \u2014 also removes vector plots/diagrams for a "
    "clean text-only PDF.",
    "Convert PDF \u2192 LaTeX \u2014 one compilable IEEEtran .tex per PDF, with "
    "title, authors, abstract, index terms, all sections/subsections, "
    "figure & table captions, \\cite{} citations and an embedded bibliography.",
    "Convert PDF \u2192 Markdown \u2014 full text, no images, ideal for feeding "
    "to AI tools.",
    "Figures (raster images and vector plots) extracted to a shared "
    "\"Latex_Resource\" folder with unique, conflict-free names.",
    "Batch processing: add many PDFs or whole folders at once.",
    "Output beside each PDF, or all to one chosen folder.",
]

HOW_TO = [
    "1. Add the PDF(s): use \"Add PDF File(s)\u2026\" or \"Add Folder\u2026\".",
    "2. Pick an Operation (required): Remove images, Convert to LaTeX, or "
    "Convert to Markdown. Nothing is selected by default.",
    "3. Set the options shown for that operation (removal sub-mode, or where "
    "to write the output).",
    "4. Click the Start button. Progress and a log appear at the bottom.",
    "5. For LaTeX output, upload the .tex and its \"Latex_Resource\" folder to "
    "Overleaf (or compile locally with pdfLaTeX).",
]

NOTES = [
    "LaTeX/Markdown conversion recovers the text and structure of the PDF; it "
    "is not a pixel-perfect reproduction. Equations are extracted as "
    "approximate plain text and may need manual review.",
    "In many IEEE papers the numeric table grids are drawn as vector graphics "
    "(not selectable text), so those values are captured as figure images "
    "rather than as text.",
]


def build_date_string():
    """Return the build date/time, falling back gracefully when not built."""
    try:
        import build_info  # generated by build_exe.bat
        return getattr(build_info, "BUILD_DATE", "Development build")
    except Exception:
        return "Development build"
